     -- custom Joker 
 return {
       j_aura_farm= {enabled = true,
       order = 1,  unlocked = false,   start_alerted = true, discovered = false, start_discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 5, sell_cost = 2, name = "Aura Farming", pos = {x=0,y=0}, set = "custom_joker", atlas = "custom_joker", effect = "Mult", cost_mult = 1.0, config = {extra = 1, mult = 0, x_mult = 1}},
       j_rugpull= {enabled = true, order = 2,  unlocked = false,   start_alerted = true, discovered = false, start_discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 2, cost = 4, sell_cost = 0, name = "Rugpull", pos = {x=1,y=0}, set = "custom_joker", atlas = "custom_joker", effect = "Bonus dollars", cost_mult = 1.0, config = {dollars = 8}},
              j_zombie_joker= {enabled = true, order = 3,  unlocked = false,   start_alerted = true, discovered = false, start_discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = false, rarity = 2, cost = 5, sell_cost = 2, name = "Zombie Joker", pos = {x=2,y=0}, set = "custom_joker", atlas = "custom_joker", effect = "Prevent Death", cost_mult = 1.0, config = {hand = 1, card = 5}},
              j_lithograph= {enabled = true, order = 4,  unlocked = false,   start_alerted = true, discovered = false, start_discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 1, cost = 3, sell_cost = 2, name = "Lithograph", pos = {x=3,y=0}, set = "custom_joker", atlas = "custom_joker", effect = "mult", cost_mult = 1.0, config = {mult = 6}},
              j_boilerplate= {enabled = true, order = 5,  unlocked = false,   start_alerted = true, discovered = false, start_discovered = false, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 3, cost = 6, sell_cost = 3, name = "Boilerplate", pos = {x=4,y=0}, set = "custom_joker", atlas = "custom_joker", effect = "halving", cost_mult = 1.0, config = {extra = 0.5}},
       j_super_joker= {enabled = false, order = 6,  unlocked = false,   start_alerted = true, discovered = true, start_discovered = true, blueprint_compat = true, perishable_compat = true, eternal_compat = true, rarity = 4, cost = 100, sell_cost = 10, name = "Super Joker", pos = {x=0,y=1}, soul_pos = {x=0, y=2}, set = "custom_joker", atlas = "custom_joker", effect = "Mult", cost_mult = 1.0, config = {mult = 1.7976931348623157e308}},
 }