return {
 z_sagitarius = {
   order = 1,
   consumeable = false,
   name = "Sagitarius", 
   pos = {x=0,y=0}, 
   set = "Zodiac",
   discovered = false,
   config = {},
   },
 z_pisces = {
   order = 2,
   consumeable = false,
   name = "Pisces", 
   pos = {x=1,y=0}, 
   set = "Zodiac",
   discovered = false,
   config = {},
   },
 z_aries = {
   order = 3,
   consumeable = false,
   name = "Aries", 
   pos = {x=2,y=0}, 
   set = "Zodiac",
   discovered = false,
   config = {extra = {chips = 15}},
   },
 z_taurus = {
   order = 4,
   consumeable = false,
   name = "Taurus", 
   pos = {x=3,y=0}, 
   set = "Zodiac", 
   discovered = false,
   config = {extra = {x_mult = 2}},
 },
 z_gemini = {
   order = 5,
   consumeable = false,
   name = "Gemini", 
   pos = {x=4,y=0}, 
   set = "Zodiac", 
   discovered = false,
   config = {},
 },
 z_cancer = {
   order = 6,
   consumeable = false,
   name = "Cancer", 
   pos = {x=5,y=0}, 
   set = "Zodiac", 
   discovered = false,
   config = {},
 },
 z_leo = {
   order = 7,
   consumeable = false,
   name = "Leo", 
   pos = {x=6,y=0}, 
   set = "Zodiac", 
   discovered = false,
   config = {extra = {prob_min = 1,prob_max = 20}},
 },
 z_capricorn = {
   order = 12,
   consumeable = false,
   name = "Capricorn", 
   pos = {x=4,y=1}, 
   set = "Zodiac", 
   discovered = false,
   config = {extra = {gain = "0.1", x_mult = 1}}
   },
}
